# fly.toml - Configuração do Fly.io para uma aplicação Next.js em Docker
app = "portfolio-upktkw" # Substitua pelo nome do seu app no Fly.io

kill_signal = "SIGINT"
kill_timeout = 5

[env]
NODE_ENV = "production" # Ambiente de execução

[build]
dockerfile = "Dockerfile" # Nome do Dockerfile usado para o build

[[services]]
internal_port = 3000 # Porta interna usada pela aplicação
protocol = "tcp"

[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.ports]]
handlers = ["http"]
port = 80           # Porta pública para HTTP

[[services.ports]]
handlers = ["tls", "http"]
port = 443                 # Porta pública para HTTPS

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
